# file: .github/workflows/show-directory.yml
name: show-directory
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Project setup
        run:  make setup
      - name: Running tests
        run: make test
      - name: Launching the linter
        run: make lint